
```{r child = 'aaa.Rmd'}

```

```{r, echo = FALSE}

n_htn <- table.glue::table_value(sum(nhanes_data$svy_subpop_htn))
n_chol <- table.glue::table_value(sum(nhanes_data$svy_subpop_chol))

```


Currently, two sub-populations are included in `nhanes_data`:

- blood pressure and hypertension (n = `r n_htn`) 

- lipids and cholesterol (n = `r n_chol`)

To access a sub-population, simply filter `nhanes_data` to contain rows where the corresponding sub-population indicator is equal to 1, e.g., 

```{r, results='hide'}

# for blood pressure and hypertension sub-population
nhanes_data[svy_subpop_htn == 1]

# for lipids and cholesterol sub-population
nhanes_data[svy_subpop_chol == 1]

```


```{r, echo=FALSE, results='asis'}

classes <-
 list("Survey" = "In each NHANES cycle, potential participants were identified using a multi-stage sampling process. The variables below are based on this process.",
      "Demographics" = "The NHANES in-home interview included questions about participant demographics, including age, sex, race/ethnicity, and pregnancy status",
      "Blood pressure" = "Systolic and diastolic BP (SBP and DBP, respectively) were measured three times by trained and certified physicians. BP was measured using a mercury sphygmomanometer from 1999-2000 through 2015-2016 and using an oscillometric device in 2017-2020. The oscillometric SBP and DBP values were calibrated to the mercury device. Mean SBP and DBP levels were computed over all available",
      "Hypertension" = "These variables are derived according to the 2017 American College of Cardiology/American Heart Association (ACC/AHA) BP guideline and the Seventh Joint National Committee (JNC7) BP guideline." ,
      "Antihypertensive medication" = "During the interview, the labels of medications that participants reported taking in the preceding 30 days were recorded.",
      "Comorbidities" = "These variables describe comorbid conditions.")

data_to_doc <- nhanes_key %>% 
 .[class %in% names(classes)] %>%
 .[variable != 'svy_subpop_chol'] %>% 
 .[variable != 'svy_weight_cal'] %>% 
 .[, class := factor(class, levels = names(classes))] %>% 
 .[order(class)] %>% 
 droplevels() %>% 
 .[, description := gsub('\u2265', '>=', x = description, fixed = T)] %>% 
 .[, label := gsub('\u2265', '>=', x = label, fixed = T)]

key_classes <- split(data_to_doc, by = 'class')

for(i in seq_along(key_classes)){
 
 cat("#", names(key_classes)[i], "variables", "\n")
 
 cat(classes[[names(key_classes)[i]]], "\n\n")
 
 for(j in seq_along(key_classes[[i]]$variable)){
  cat("##", key_classes[[i]]$variable[j], "\n")
  cat("- **Label**: ", key_classes[[i]]$label[j], "\n")
  cat("- **Description**: ", key_classes[[i]]$description[j], "\n")
  
  if(names(key_classes)[i] != 'Survey'){
   cat(get_variable_summary(key_classes[[i]]$variable[j],
                            data = nhanes_data[svy_subpop_htn == 1]),
       "\n\n")
  } else {
   cat("\n")
  }
  
  
 }
 
}

```

