---
title: "Blood pressure control, JNC7 definition"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Blood pressure control, JNC7 definition}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.height = 6,
  fig.width = 7.9,
  echo = FALSE
)
```

```{r setup}
library(cardioStatsUSA)

subset_variables <- list("htn_jnc7", 
                         "demo_pregnant")

subset_values <- list("Yes", 
                      c("No", "Missing"))

```

## BP control (JNC7 BP guideline definition)

According to the FILL IN, BP control is defined as having systolic BP < 140 mm Hg and diastolic BP < 90 mm Hg.

### Proportion with BP control by calendar year.

```{r}
nhanes_visualize(outcome = 'bp_control_jnc7', 
                 subset_variables = subset_variables,
                 subset_values = subset_values,
                 years = 'all')[[1]]
```

### Proportion with BP control by age group in 2017-2020.

```{r}

nhanes_visualize(outcome = 'bp_control_jnc7', 
                 exposure = 'demo_age_cat',
                 subset_variables = subset_variables,
                 subset_values = subset_values,
                 years = 'most_recent')[[1]]
```

### Proportion with BP control by sex in 2017-2020.

```{r}
nhanes_visualize(outcome = 'bp_control_jnc7', 
                 exposure = 'demo_gender',
                 subset_variables = subset_variables,
                 subset_values = subset_values,
                 years = 'most_recent')[[1]]
```


### Proportion with BP control by race/ethnicity in 2017-2020.

```{r}
nhanes_visualize(outcome = 'bp_control_jnc7', 
                 exposure = 'demo_race',
                 subset_variables = subset_variables,
                 subset_values = subset_values,
                 years = 'most_recent')[[1]]
```

