---
title: "Blood pressure levels"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Blood pressure levels}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.height = 6,
  fig.width = 7.9,
  echo = FALSE
)

```


```{r setup}
library(cardioStatsUSA)
```

## Who is included in this analysis



## Systolic blood pressure

### Mean levels by calendar year.

```{r}
nhanes_visualize(outcome = 'bp_sys_mean', 
                 years = 'all')[[1]]
```

### Mean levels by age group in 2017-2020.

```{r}
nhanes_visualize(outcome = 'bp_sys_mean',
                 exposure = 'demo_age_cat',
                 years = 'most_recent')[[1]]
```

### Mean levels by sex in 2017-2020.

```{r}
nhanes_visualize(outcome = 'bp_sys_mean',
                 exposure = 'demo_gender',
                 years = 'most_recent')[[1]]
```


### Mean levels by race/ethnicity in 2017-2020.

```{r}
nhanes_visualize(outcome = 'bp_sys_mean',
                 exposure = 'demo_race',
                 years = 'most_recent')[[1]]
```

## Diastolic blood pressure

### Mean levels by calendar year.

```{r}
nhanes_visualize(outcome = 'bp_dia_mean', 
                 years = 'all')[[1]]
```

### Mean levels by age group in 2017-2020.

```{r}
nhanes_visualize(outcome = 'bp_dia_mean',
                 exposure = 'demo_age_cat',
                 years = 'most_recent')[[1]]
```

### Mean levels by sex in 2017-2020.

```{r}
nhanes_visualize(outcome = 'bp_dia_mean',
                 exposure = 'demo_gender',
                 years = 'most_recent')[[1]]
```


### Mean levels by race/ethnicity in 2017-2020.

```{r}
nhanes_visualize(outcome = 'bp_dia_mean',
                 exposure = 'demo_race',
                 years = 'most_recent')[[1]]
```





